### ISSUE TITLE
Video?

### ISSUE THREAD

**Issue by amrrs** [jgoerner/beyond-jupyter#1]
Hey, @jgoerner  Amazing slides! Is there a video recording of it?

**Comment by jgoerner** [comment]
Thank for your interest @amrrs . As soon as the video is provided by the PyCon Team I will adjust the Readme and close this issue.

**Comment by amrrs** [comment]
Thanks @jgoerner  That's very nice of you!

**Comment by jgoerner** [comment]
@amrrs I've just included the video in the Readme, happy watching :-)

**Comment by amrrs** [comment]
Wow thank you so much :)
